/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Session } from './Session';
import {
    SessionFromJSON,
    SessionFromJSONTyped,
    SessionToJSON,
    SessionToJSONTyped,
} from './Session';

/**
 * 
 * @export
 * @interface SessionListApiResponse
 */
export interface SessionListApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SessionListApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SessionListApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {Array<Session>}
     * @memberof SessionListApiResponse
     */
    data?: Array<Session> | null;
}

/**
 * Check if a given object implements the SessionListApiResponse interface.
 */
export function instanceOfSessionListApiResponse(value: object): value is SessionListApiResponse {
    return true;
}

export function SessionListApiResponseFromJSON(json: any): SessionListApiResponse {
    return SessionListApiResponseFromJSONTyped(json, false);
}

export function SessionListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SessionFromJSON)),
    };
}

export function SessionListApiResponseToJSON(json: any): SessionListApiResponse {
    return SessionListApiResponseToJSONTyped(json, false);
}

export function SessionListApiResponseToJSONTyped(value?: SessionListApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SessionToJSON)),
    };
}

